language: swift
osx_image: xcode9.0

#rvm: 2.2.2
before_install:
   - gem install cocoapods -v '1.2.1'
#    - pod repo update
    
podfile: Example/Podfile
xcode_workspace: Example/StaticWebsiteGeneratorExample.xcworkspace
xcode_scheme: StaticWebsiteGeneratorExample
#xcode_sdk: 
#    - iphonesimulator
#    - macosx

script:
    - pod --version
    - xcodebuild test -workspace Example/StaticWebsiteGeneratorExample.xcworkspace -scheme StaticWebsiteGeneratorExample  